"""users them tao_luc

Revision ID: 040595cbe601
Revises: e2a75c1c5e82
Create Date: 2026-07-20 19:26:27.929576

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# Autogenerate sinh `app.db.types.UTCDateTime()` nhưng KHÔNG tự thêm import này → thiếu là
# NameError lúc chạy migration. Lỗi tái diễn với mọi kiểu cột tùy biến, luôn phải kiểm tay.
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '040595cbe601'
down_revision: Union[str, Sequence[str], None] = 'e2a75c1c5e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NULLABLE có chủ ý: tài khoản có TRƯỚC cột này không biết ngày tạo thật, để NULL trung
    # thực hơn là gán bừa thời điểm chạy migration (sẽ làm mọi thống kê theo ngày sai lệch).
    op.add_column('users', sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tao_luc')
    # ### end Alembic commands ###
