"""muc_tieu them cot muc_con

Revision ID: 0e5e53d3e3b3
Revises: 2929ecbc70fc
Create Date: 2026-07-18 16:52:40.505476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5e53d3e3b3'
down_revision: Union[str, Sequence[str], None] = '2929ecbc70fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muc_tieu', sa.Column('muc_con', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muc_tieu', 'muc_con')
    # ### end Alembic commands ###
