"""baseline gop toan bo schema hien tai

Revision ID: 2929ecbc70fc
Revises: 
Create Date: 2026-07-17 22:18:30.668434

"""
from typing import Sequence, Union

import sqlalchemy as sa

import app.db.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2929ecbc70fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cau_hinh',
    sa.Column('khoa', sa.String(length=100), nullable=False),
    sa.Column('gia_tri', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('khoa')
    )
    op.create_table('llm_su_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngay', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('loai', sa.String(length=20), nullable=False),
    sa.Column('so_luot', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ngay', 'user_id', 'loai', name='uq_llm_su_dung')
    )
    op.create_index(op.f('ix_llm_su_dung_id'), 'llm_su_dung', ['id'], unique=False)
    op.create_index(op.f('ix_llm_su_dung_ngay'), 'llm_su_dung', ['ngay'], unique=False)
    # lop.gv_id -> users.id VÀ users.lop_id -> lop.id là FK VÒNG TRÒN (autogenerate cảnh báo
    # "unresolvable cycles"): tạo 'lop' TRƯỚC 'users' nhưng KHÔNG kèm FK gv_id ngay (bảng
    # users chưa tồn tại) — thêm constraint đó bằng op.create_foreign_key() SAU KHI 'users'
    # đã tạo xong, để tránh lỗi "relation users does not exist" trên Postgres.
    op.create_table('lop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('gv_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lop_id'), 'lop', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vai_tro', sa.Enum('admin', 'gv', 'hs', name='vaitro'), nullable=False),
    sa.Column('ho_ten', sa.String(length=200), nullable=False),
    sa.Column('dang_nhap', sa.String(length=100), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=200), nullable=False),
    sa.Column('trang_thai', sa.Enum('hoat_dong', 'khoa', name='trangthaiuser'), nullable=False),
    sa.Column('la_quan_ly', sa.Boolean(), nullable=False),
    sa.Column('lop_id', sa.Integer(), nullable=True),
    sa.Column('da_xem_huong_dan_phong_hoc', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lop_id'], ['lop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dang_nhap'), 'users', ['dang_nhap'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # batch_alter_table (thay vì op.create_foreign_key trần) để cùng chạy được trên cả
    # SQLite (không hỗ trợ ALTER TABLE ADD CONSTRAINT trực tiếp, cần "rebuild" bảng) lẫn
    # Postgres (ALTER TABLE ADD CONSTRAINT thẳng, batch mode không đổi hành vi).
    with op.batch_alter_table('lop') as batch_op:
        batch_op.create_foreign_key('fk_lop_gv_id_users', 'users', ['gv_id'], ['id'])
    op.create_table('chuyen_de',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=200), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('nguoi_tao_id', sa.Integer(), nullable=True),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_tao_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nguoi_tao_id', 'ten', name='uq_chuyende_nguoitao_ten')
    )
    op.create_index(op.f('ix_chuyen_de_id'), 'chuyen_de', ['id'], unique=False)
    op.create_table('cot_moc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('loai', sa.String(length=50), nullable=False),
    sa.Column('tieu_de', sa.String(length=200), nullable=False),
    sa.Column('mo_ta', sa.String(length=500), nullable=True),
    sa.Column('dat_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cot_moc_hoc_sinh_id'), 'cot_moc', ['hoc_sinh_id'], unique=False)
    op.create_index(op.f('ix_cot_moc_id'), 'cot_moc', ['id'], unique=False)
    op.create_table('de_thi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=200), nullable=False),
    sa.Column('nguoi_tao_id', sa.Integer(), nullable=False),
    sa.Column('thoi_gian_phut', sa.Integer(), nullable=False),
    sa.Column('phat_hanh', sa.Boolean(), nullable=False),
    sa.Column('pham_vi', sa.String(length=16), nullable=False),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('phat_hanh_luc', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('thu_hoi_luc', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_tao_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_thi_id'), 'de_thi', ['id'], unique=False)
    op.create_table('nhiem_vu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gv_id', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=200), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('han_chot', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gv_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nhiem_vu_gv_id'), 'nhiem_vu', ['gv_id'], unique=False)
    op.create_index(op.f('ix_nhiem_vu_id'), 'nhiem_vu', ['id'], unique=False)
    op.create_table('phan_tich_hs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('noi_dung_hs', sa.Text(), nullable=True),
    sa.Column('noi_dung_gv', sa.Text(), nullable=True),
    sa.Column('so_bai_luc_tao', sa.Integer(), nullable=False),
    sa.Column('nguon', sa.String(length=16), nullable=False),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hoc_sinh_id', name='uq_phantich_hs')
    )
    op.create_index(op.f('ix_phan_tich_hs_id'), 'phan_tich_hs', ['id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('chuyen_de', sa.String(length=200), nullable=False),
    sa.Column('so_bai_lam', sa.Integer(), nullable=False),
    sa.Column('so_bai_hoan_thanh', sa.Integer(), nullable=False),
    sa.Column('ty_le_dung_trung_binh', sa.Float(), nullable=False),
    sa.Column('tong_thoi_gian_giay', sa.Integer(), nullable=False),
    sa.Column('cap_nhat_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hoc_sinh_id', 'chuyen_de', name='uq_progress_hs_chuyende')
    )
    op.create_index(op.f('ix_progress_id'), 'progress', ['id'], unique=False)
    op.create_table('thong_bao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_nhan_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_gui_id', sa.Integer(), nullable=True),
    sa.Column('loai', sa.Enum('nhan_xet', 'co', 'nhiem_vu', 'nho_tro_giup', 'tra_loi', 'quan_ly', 'he_thong', name='loaithongbao'), nullable=False),
    sa.Column('tieu_de', sa.String(length=200), nullable=True),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('lien_ket_loai', sa.String(length=32), nullable=True),
    sa.Column('lien_ket_id', sa.Integer(), nullable=True),
    sa.Column('da_doc', sa.Boolean(), nullable=False),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_gui_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nguoi_nhan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thong_bao_id'), 'thong_bao', ['id'], unique=False)
    op.create_index(op.f('ix_thong_bao_nguoi_nhan_id'), 'thong_bao', ['nguoi_nhan_id'], unique=False)
    op.create_table('bai_thi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('de_thi_id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Enum('dang_thi', 'da_nop', name='trangthaibaithi'), nullable=False),
    sa.Column('bat_dau_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('nop_luc', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('bai_lam', sa.JSON(), nullable=False),
    sa.Column('diem', sa.Float(), nullable=True),
    sa.Column('diem_toi_da', sa.Float(), nullable=True),
    sa.Column('chi_tiet', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['de_thi_id'], ['de_thi.id'], ),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bai_thi_id'), 'bai_thi', ['id'], unique=False)
    op.create_table('dang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chuyen_de_id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=200), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('nguoi_tao_id', sa.Integer(), nullable=True),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chuyen_de_id'], ['chuyen_de.id'], ),
    sa.ForeignKeyConstraint(['nguoi_tao_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chuyen_de_id', 'ten', name='uq_dang_chuyende_ten')
    )
    op.create_index(op.f('ix_dang_chuyen_de_id'), 'dang', ['chuyen_de_id'], unique=False)
    op.create_index(op.f('ix_dang_id'), 'dang', ['id'], unique=False)
    op.create_table('de_thi_hoc_sinh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('de_thi_id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['de_thi_id'], ['de_thi.id'], ),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_thi_hoc_sinh_de_thi_id'), 'de_thi_hoc_sinh', ['de_thi_id'], unique=False)
    op.create_index(op.f('ix_de_thi_hoc_sinh_hoc_sinh_id'), 'de_thi_hoc_sinh', ['hoc_sinh_id'], unique=False)
    op.create_index(op.f('ix_de_thi_hoc_sinh_id'), 'de_thi_hoc_sinh', ['id'], unique=False)
    op.create_table('nhiem_vu_hoc_sinh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhiem_vu_id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nhiem_vu_id'], ['nhiem_vu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nhiem_vu_hoc_sinh_hoc_sinh_id'), 'nhiem_vu_hoc_sinh', ['hoc_sinh_id'], unique=False)
    op.create_index(op.f('ix_nhiem_vu_hoc_sinh_id'), 'nhiem_vu_hoc_sinh', ['id'], unique=False)
    op.create_index(op.f('ix_nhiem_vu_hoc_sinh_nhiem_vu_id'), 'nhiem_vu_hoc_sinh', ['nhiem_vu_id'], unique=False)
    op.create_table('muc_tieu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_tao_id', sa.Integer(), nullable=True),
    sa.Column('nguon', sa.String(length=16), nullable=False),
    sa.Column('loai', sa.String(length=16), nullable=False),
    sa.Column('tieu_de', sa.String(length=200), nullable=False),
    sa.Column('dang_id', sa.Integer(), nullable=True),
    sa.Column('chuyen_de', sa.String(length=200), nullable=True),
    sa.Column('chi_tieu_so', sa.Integer(), nullable=False),
    sa.Column('moc_bat_dau', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('han', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('da_huy', sa.Boolean(), nullable=False),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dang_id'], ['dang.id'], ),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nguoi_tao_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muc_tieu_hoc_sinh_id'), 'muc_tieu', ['hoc_sinh_id'], unique=False)
    op.create_index(op.f('ix_muc_tieu_id'), 'muc_tieu', ['id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chuyen_de', sa.String(length=200), nullable=False),
    sa.Column('dang_id', sa.Integer(), nullable=True),
    sa.Column('loai_cau', sa.Enum('TN4PA', 'TNDS', 'TLN', name='loaicau'), nullable=False),
    sa.Column('do_kho', sa.Enum('de', 'tb', 'kho', name='dokho'), nullable=False),
    sa.Column('de_bai', sa.Text(), nullable=False),
    sa.Column('hinh_anh', sa.String(length=300), nullable=True),
    sa.Column('loai_dap_an_nhap', sa.String(length=50), nullable=False),
    sa.Column('che_do_so_khop', sa.Enum('tuong_duong', 'dung_dang', name='chedosokhopenum'), nullable=False),
    sa.Column('trang_thai_duyet', sa.Enum('cho_duyet', 'da_duyet', 'loai', name='trangthaiduyet'), nullable=False),
    sa.Column('nguon', sa.Enum('gv_nhap', 'ai_sinh', name='nguon'), nullable=False),
    sa.Column('nguoi_tao_id', sa.Integer(), nullable=True),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('bi_an', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('loi_giai_chi_tiet', sa.Text(), nullable=False),
    sa.Column('hien_loi_giai_chi_tiet', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dang_id'], ['dang.id'], ),
    sa.ForeignKeyConstraint(['nguoi_tao_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_dang_id'), 'problems', ['dang_id'], unique=False)
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_table('tom_tat_ly_thuyet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chuyen_de_id', sa.Integer(), nullable=False),
    sa.Column('dang_id', sa.Integer(), nullable=True),
    sa.Column('tieu_de', sa.String(length=200), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('tu_khoa', sa.JSON(), nullable=False),
    sa.Column('hien', sa.Boolean(), nullable=False),
    sa.Column('nguoi_tao_id', sa.Integer(), nullable=True),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('cap_nhat_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chuyen_de_id'], ['chuyen_de.id'], ),
    sa.ForeignKeyConstraint(['dang_id'], ['dang.id'], ),
    sa.ForeignKeyConstraint(['nguoi_tao_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tom_tat_ly_thuyet_chuyen_de_id'), 'tom_tat_ly_thuyet', ['chuyen_de_id'], unique=False)
    op.create_index(op.f('ix_tom_tat_ly_thuyet_dang_id'), 'tom_tat_ly_thuyet', ['dang_id'], unique=False)
    op.create_index(op.f('ix_tom_tat_ly_thuyet_id'), 'tom_tat_ly_thuyet', ['id'], unique=False)
    op.create_table('de_thi_cau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('de_thi_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('phan', sa.String(length=5), nullable=False),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('diem_cau', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['de_thi_id'], ['de_thi.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_de_thi_cau_id'), 'de_thi_cau', ['id'], unique=False)
    op.create_table('nhiem_vu_bai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nhiem_vu_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nhiem_vu_id'], ['nhiem_vu.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nhiem_vu_bai_id'), 'nhiem_vu_bai', ['id'], unique=False)
    op.create_index(op.f('ix_nhiem_vu_bai_nhiem_vu_id'), 'nhiem_vu_bai', ['nhiem_vu_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Enum('dang_lam', 'hoan_thanh', 'bo_do', name='trangthaisession'), nullable=False),
    sa.Column('buoc_hien_tai', sa.Integer(), nullable=False),
    sa.Column('y_hien_tai', sa.String(length=10), nullable=True),
    sa.Column('trang_thai_y', sa.JSON(), nullable=True),
    sa.Column('cap_goi_y_hien_tai', sa.Integer(), nullable=False),
    sa.Column('so_lan_sai_lien_tiep', sa.Integer(), nullable=False),
    sa.Column('so_lan_khong_hieu', sa.Integer(), nullable=False),
    sa.Column('tong_so_lan_sai', sa.Integer(), nullable=False),
    sa.Column('so_lan_het_goi_y', sa.Integer(), nullable=False),
    sa.Column('so_lan_xem_ly_thuyet', sa.Integer(), nullable=False),
    sa.Column('diem_qua_trinh', sa.Float(), nullable=True),
    sa.Column('so_y_dung', sa.Integer(), nullable=False),
    sa.Column('da_suy_luan', sa.Boolean(), nullable=False),
    sa.Column('thoi_gian_y', sa.JSON(), nullable=True),
    sa.Column('diem', sa.Float(), nullable=True),
    sa.Column('bat_dau_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('thoi_gian_hoat_dong_giay', sa.Integer(), nullable=True),
    sa.Column('thoi_gian_giay', sa.Integer(), nullable=True),
    sa.Column('cap_nhat_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('bi_an', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('solution_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('pham_vi', sa.String(length=10), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=False),
    sa.Column('bieu_thuc_ket_qua', sa.String(length=500), nullable=False),
    sa.Column('danh_sach_goi_y', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_steps_id'), 'solution_steps', ['id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('vai_tro', sa.Enum('hoc_sinh', 'gia_su', 'giao_vien', name='vaitroturn'), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('dap_an_nhap', sa.Text(), nullable=True),
    sa.Column('ket_qua_so_khop', sa.JSON(), nullable=True),
    sa.Column('cap_goi_y', sa.Integer(), nullable=False),
    sa.Column('co_bi_chot_chan', sa.Boolean(), nullable=False),
    sa.Column('thoi_diem', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_id'), 'turns', ['id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('loai_co', sa.Enum('ro_ri_dap_an', 'noi_dung_khong_phu_hop', 'ngoai_pham_vi', 'khong_hieu_nhieu', 'chot_chan_nhieu', 'thu_cong', name='loaico'), nullable=False),
    sa.Column('trang_thai', sa.Enum('cho_xu_ly', 'da_xu_ly', 'bo_qua', name='trangthaico'), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('xu_ly_boi', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_id'), 'flags', ['id'], unique=False)
    op.create_table('yeu_cau_tro_giup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('buoc', sa.Integer(), nullable=True),
    sa.Column('y', sa.String(length=10), nullable=True),
    sa.Column('noi_dung', sa.Text(), nullable=True),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('trang_thai', sa.Enum('cho_xu_ly', 'da_tra_loi', name='trangthaitrogiup'), nullable=False),
    sa.Column('tra_loi', sa.Text(), nullable=True),
    sa.Column('gv_id', sa.Integer(), nullable=True),
    sa.Column('tao_luc', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('tra_loi_luc', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gv_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yeu_cau_tro_giup_hoc_sinh_id'), 'yeu_cau_tro_giup', ['hoc_sinh_id'], unique=False)
    op.create_index(op.f('ix_yeu_cau_tro_giup_id'), 'yeu_cau_tro_giup', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yeu_cau_tro_giup_id'), table_name='yeu_cau_tro_giup')
    op.drop_index(op.f('ix_yeu_cau_tro_giup_hoc_sinh_id'), table_name='yeu_cau_tro_giup')
    op.drop_table('yeu_cau_tro_giup')
    op.drop_index(op.f('ix_flags_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_turns_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_solution_steps_id'), table_name='solution_steps')
    op.drop_table('solution_steps')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_nhiem_vu_bai_nhiem_vu_id'), table_name='nhiem_vu_bai')
    op.drop_index(op.f('ix_nhiem_vu_bai_id'), table_name='nhiem_vu_bai')
    op.drop_table('nhiem_vu_bai')
    op.drop_index(op.f('ix_de_thi_cau_id'), table_name='de_thi_cau')
    op.drop_table('de_thi_cau')
    op.drop_index(op.f('ix_tom_tat_ly_thuyet_id'), table_name='tom_tat_ly_thuyet')
    op.drop_index(op.f('ix_tom_tat_ly_thuyet_dang_id'), table_name='tom_tat_ly_thuyet')
    op.drop_index(op.f('ix_tom_tat_ly_thuyet_chuyen_de_id'), table_name='tom_tat_ly_thuyet')
    op.drop_table('tom_tat_ly_thuyet')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_dang_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_muc_tieu_id'), table_name='muc_tieu')
    op.drop_index(op.f('ix_muc_tieu_hoc_sinh_id'), table_name='muc_tieu')
    op.drop_table('muc_tieu')
    op.drop_index(op.f('ix_nhiem_vu_hoc_sinh_nhiem_vu_id'), table_name='nhiem_vu_hoc_sinh')
    op.drop_index(op.f('ix_nhiem_vu_hoc_sinh_id'), table_name='nhiem_vu_hoc_sinh')
    op.drop_index(op.f('ix_nhiem_vu_hoc_sinh_hoc_sinh_id'), table_name='nhiem_vu_hoc_sinh')
    op.drop_table('nhiem_vu_hoc_sinh')
    op.drop_index(op.f('ix_de_thi_hoc_sinh_id'), table_name='de_thi_hoc_sinh')
    op.drop_index(op.f('ix_de_thi_hoc_sinh_hoc_sinh_id'), table_name='de_thi_hoc_sinh')
    op.drop_index(op.f('ix_de_thi_hoc_sinh_de_thi_id'), table_name='de_thi_hoc_sinh')
    op.drop_table('de_thi_hoc_sinh')
    op.drop_index(op.f('ix_dang_id'), table_name='dang')
    op.drop_index(op.f('ix_dang_chuyen_de_id'), table_name='dang')
    op.drop_table('dang')
    op.drop_index(op.f('ix_bai_thi_id'), table_name='bai_thi')
    op.drop_table('bai_thi')
    op.drop_index(op.f('ix_thong_bao_nguoi_nhan_id'), table_name='thong_bao')
    op.drop_index(op.f('ix_thong_bao_id'), table_name='thong_bao')
    op.drop_table('thong_bao')
    op.drop_index(op.f('ix_progress_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_phan_tich_hs_id'), table_name='phan_tich_hs')
    op.drop_table('phan_tich_hs')
    op.drop_index(op.f('ix_nhiem_vu_id'), table_name='nhiem_vu')
    op.drop_index(op.f('ix_nhiem_vu_gv_id'), table_name='nhiem_vu')
    op.drop_table('nhiem_vu')
    op.drop_index(op.f('ix_de_thi_id'), table_name='de_thi')
    op.drop_table('de_thi')
    op.drop_index(op.f('ix_cot_moc_id'), table_name='cot_moc')
    op.drop_index(op.f('ix_cot_moc_hoc_sinh_id'), table_name='cot_moc')
    op.drop_table('cot_moc')
    op.drop_index(op.f('ix_chuyen_de_id'), table_name='chuyen_de')
    op.drop_table('chuyen_de')
    with op.batch_alter_table('lop') as batch_op:
        batch_op.drop_constraint('fk_lop_gv_id_users', type_='foreignkey')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_dang_nhap'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lop_id'), table_name='lop')
    op.drop_table('lop')
    op.drop_index(op.f('ix_llm_su_dung_ngay'), table_name='llm_su_dung')
    op.drop_index(op.f('ix_llm_su_dung_id'), table_name='llm_su_dung')
    op.drop_table('llm_su_dung')
    op.drop_table('cau_hinh')
    # ### end Alembic commands ###
