"""turns them cot buoc va y

Revision ID: b931a26780f4
Revises: fa758f2e3937
Create Date: 2026-07-27 10:57:54.389043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b931a26780f4'
down_revision: Union[str, Sequence[str], None] = 'fa758f2e3937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('buoc', sa.Integer(), nullable=True))
    op.add_column('turns', sa.Column('y', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'y')
    op.drop_column('turns', 'buoc')
    # ### end Alembic commands ###
